// A fixed 8-color palette for tinting sections on the table layout canvas.
// Only the index into this array is ever stored (sections.color_index) -
// the actual hues live entirely here, so they can be retuned without a
// data migration.
//
// Generated by stepping through hue space by the golden-angle conjugate,
// which is the standard technique for "each next color should be maximally
// distinct from every color picked so far" - so index 0 is the most
// distinct pick, index 1 the next-most-distinct given index 0 exists, etc.
// Hues are restricted to two bands that avoid the app's reserved
// accent/status hues (orange ~25deg, amber ~38deg, red ~0deg, green
// ~142deg - see globals.css) so a section's color never gets confused with
// the brand accent or a reservation/order status, including the green/red
// availability border planned for tables later.
const SECTION_COLOR_COUNT = 8;
const GOLDEN_RATIO_CONJUGATE = 0.6180339887498949;
const HUE_BANDS: readonly [start: number, end: number][] = [
  [50, 110],
  [160, 345],
];
const TOTAL_BAND_LENGTH = HUE_BANDS.reduce((sum, [start, end]) => sum + (end - start), 0);

function hueForIndex(index: number): number {
  let remaining = ((index * GOLDEN_RATIO_CONJUGATE) % 1) * TOTAL_BAND_LENGTH;
  for (const [start, end] of HUE_BANDS) {
    const length = end - start;
    if (remaining < length) return start + remaining;
    remaining -= length;
  }
  return HUE_BANDS[0][0];
}

export function sectionColor(index: number): string {
  const wrapped = ((index % SECTION_COLOR_COUNT) + SECTION_COLOR_COUNT) % SECTION_COLOR_COUNT;
  const hue = hueForIndex(wrapped);
  // Indices 4-6 sit close in hue to one of 0-3 (the golden-angle sequence
  // naturally bisects the gaps left by the first few picks) - bumped
  // saturation/lightness makes them read as a clearly different, bolder
  // family of color instead of a washed-out near-duplicate, without
  // touching the hues themselves (0-3 and 7 already read as distinct).
  const [saturation, lightness] = wrapped >= 4 && wrapped <= 6 ? [85, 65] : [60, 55];
  return `hsl(${hue.toFixed(1)} ${saturation}% ${lightness}%)`;
}

// Picks the least-used color index among `counts` (one entry per palette
// slot), ties broken toward the lowest index. A plain used/unused flag
// only works until every color's been used once - this is the strict
// generalization that keeps working after that: a freed-up index (count
// back to 0) is the unique minimum, so the next new section reclaims it
// immediately; once nothing is free, sections cycle evenly through the
// palette instead of piling onto index 0.
export function pickLeastUsedColorIndex(counts: readonly number[]): number {
  let bestIndex = 0;
  let bestCount = counts[0] ?? 0;
  for (let i = 1; i < SECTION_COLOR_COUNT; i++) {
    const count = counts[i] ?? 0;
    if (count < bestCount) {
      bestCount = count;
      bestIndex = i;
    }
  }
  return bestIndex;
}

export function countColorUsage(colorIndexes: readonly number[]): number[] {
  const counts = new Array(SECTION_COLOR_COUNT).fill(0);
  for (const index of colorIndexes) {
    counts[index] = (counts[index] ?? 0) + 1;
  }
  return counts;
}
